### ISSUE TITLE
Empty SRS - wmsops-getmap-each-layer

### ISSUE THREAD

**Issue by emoiroux** [opengeospatial/ets-wms11#43]
Hi,

The following test "wms:wmsops-getmap-each-layer" fails because the SrS is empty in the request.
URL: http://my_wms_server/wms1_1_1/wms?&LaYeRs=WMS1.1.1&SrS=&BbOx=0,0,1,1&WiDtH=100&ReQuEsT=GetMap&StYlEs=&HeIgHt=100&FoRmAt=image%2Fpng&VeRsIoN=1.1.1

Here is my configuration :
Service : http://my_wms_server/wms1_1_1/wms?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities
Platform : http://cite.opengeospatial.org/te2
Service : WMS 1.1.1 rev.1.10

Similar issue : https://github.com/opengeospatial/ets-wms13/issues/6

Thanks, 
Etienne

**Comment by dstenger** [comment]
The SRS is empty because the root layer is selected for this test (correct, as the root layer is requestable), but when the SRS is determined, the root layer is not considered anymore. This leads to the fact that no SRS can be found and the request is send without SRS.

There are two solutions:
1. You could remove the Name element from the root layer, so that it is not requestable anymore. Then, the test should not fail anymore.
2. The test suite can be fixed.

**Comment by dstenger** [comment]
In case a fix is needed, we need a working service URL to verify the fix.

**Comment by emoiroux** [comment]
Hi, 

It would be great to have a fix. Can you contact me via email (emoiroux@k2geospatial.com) and then I will give to you the wms server address), 

Thanks, 
Etienne

**Comment by emoiroux** [comment]
Hi, 

It would be great to have a fix. Can you contact me via email (emoiroux@k2geospatial.com) and then I will give to you the wms server address. 

Thanks, 
Etienne

**Comment by bermud** [comment]
@dstenger has this been coordinated/fixed?

**Comment by bermud** [comment]
Great to know that this is in progress.

**Comment by dstenger** [comment]
A fix for this issue was created and tested successfully (with service provided by emoiroux).

Fix is part of following pull request #46 and will be part of the next release.

**Comment by dstenger** [comment]
Pull request was merged successfully into master branch and is part of the upcoming release.
